version: "3.8"
services:
  api:
    image: graphninja/blog_api
    ports:
      - "9090:9090"
    environment:
        POSTGRES_DB: blog
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_password
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - postgres_user
      - postgres_password
volumes:
  db-data:
secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
