// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package model

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type accountTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *accountTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("account").
func (v *accountTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *accountTableType) Columns() []string {
	return []string{"id", "email", "role", "password"}
}

// NewStruct makes a new struct for that view or table.
func (v *accountTableType) NewStruct() reform.Struct {
	return new(Account)
}

// NewRecord makes a new record for that table.
func (v *accountTableType) NewRecord() reform.Record {
	return new(Account)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *accountTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// AccountTable represents account view or table in SQL database.
var AccountTable = &accountTableType{
	s: parse.StructInfo{Type: "Account", SQLSchema: "", SQLName: "account", Fields: []parse.FieldInfo{{Name: "Id", Type: "int", Column: "id"}, {Name: "Email", Type: "string", Column: "email"}, {Name: "Role", Type: "string", Column: "role"}, {Name: "Password", Type: "string", Column: "password"}}, PKFieldIndex: 0},
	z: new(Account).Values(),
}

// String returns a string representation of this struct or record.
func (s Account) String() string {
	res := make([]string, 4)
	res[0] = "Id: " + reform.Inspect(s.Id, true)
	res[1] = "Email: " + reform.Inspect(s.Email, true)
	res[2] = "Role: " + reform.Inspect(s.Role, true)
	res[3] = "Password: " + reform.Inspect(s.Password, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Account) Values() []interface{} {
	return []interface{}{
		s.Id,
		s.Email,
		s.Role,
		s.Password,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Account) Pointers() []interface{} {
	return []interface{}{
		&s.Id,
		&s.Email,
		&s.Role,
		&s.Password,
	}
}

// View returns View object for that struct.
func (s *Account) View() reform.View {
	return AccountTable
}

// Table returns Table object for that record.
func (s *Account) Table() reform.Table {
	return AccountTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Account) PKValue() interface{} {
	return s.Id
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Account) PKPointer() interface{} {
	return &s.Id
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Account) HasPK() bool {
	return s.Id != AccountTable.z[AccountTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Account) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.Id = int(i64)
	} else {
		s.Id = pk.(int)
	}
}

// check interfaces
var (
	_ reform.View   = AccountTable
	_ reform.Struct = (*Account)(nil)
	_ reform.Table  = AccountTable
	_ reform.Record = (*Account)(nil)
	_ fmt.Stringer  = (*Account)(nil)
)

func init() {
	parse.AssertUpToDate(&AccountTable.s, new(Account))
}
